name: SonarCloud
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11' # Usa la versione JDK appropriata per il tuo progetto
      - name: Cache SonarCloud
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-${{ hashFiles('**/sonar-project.properties') }}
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -DprojectKey=alessiosechi_WastelligentScheletro
            -Dorganization=alessiosechi
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
