name: SonarCloud

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3  # Aggiornato da v2 a v3

      - name: Setup JDK
        uses: actions/setup-java@v3  # Aggiornato da v1 a v3
        with:
          java-version: '11' # Usa la versione JDK appropriata per il tuo progetto

      - name: Cache SonarCloud
        uses: actions/cache@v3  # Aggiornato da v2 a v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-${{ hashFiles('**/sonar-project.properties') }}

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1  # Aggiornato da master a v1
        with:
          args: >
            -DprojectKey=alessiosechi_WastelligentScheletro
            -Dorganization=alessiosechi
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
