name: SonarCloud
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3 # Aggiorna a v3
      - name: Setup JDK
        uses: actions/setup-java@v3 # Aggiorna a v3
        with:
          java-version: '21' # Usa Java 21
          distribution: 'temurin' # O 'zulu' se vuoi usare Zulu
      - name: Cache SonarCloud
        uses: actions/cache@v3 # Aggiorna a v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar-${{ hashFiles('**/sonar-project.properties') }}
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -DprojectKey=alessiosechi_WastelligentScheletro
            -Dorganization=alessiosechi
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
