name: SonarCloud Analysis

on:
  push:
    branches:
      - master  # Cambia se hai un branch principale diverso
  pull_request:
    branches:
      - master  # Cambia se hai un branch principale diverso

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'  # Puoi cambiare la versione se necessario

      - name: Compile Java Files
        run: |
          mkdir -p out  # Crea la directory di output se non esiste
          javac -d out $(find src -name "*.java")  # Compila tutti i file .java nella directory src

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
